#!/usr/bin/env python
"""visualizer for collision_tester and collision

visualize fname boxsize 

or

visualize fname boxsize true

for labels

Creates a png file with the image.
"""
import pylab
import sys
import matplotlib.patches as mpatches

def makepic(fname,wid=5,box=[],extend=10,labels=False,bubble=False):
    Pos=[]
    Vel=[]
    Names=[]
    for line in  open(fname):
        licid,x,y,vx,vy = line.split()
        Pos.append((float(x),float(y)))
        Vel.append((float(vx),float(vy)))
        Names.append(licid)

    fig,ax = pylab.subplots(figsize=(5,5))
    if box:
        ax.set_xlim(box[0],box[1])
        ax.set_ylim(box[2],box[3])
   
    base,_=fname.split('.')
    ofile = base+'.png'
    for r,v,n in zip(Pos,Vel,Names):
        pylab.plot(*r,'bo')
        ax.add_patch(mpatches.Arrow(*r,extend*v[0],extend*v[1],width=wid,color='red'))
        if labels:
            ax.text(*r,n)
        if bubble:
            ax.add_patch(mpatches.Circle(r,5,color='green',alpha=0.5))
    ax.set_aspect('equal')
    pylab.savefig(ofile)
    pylab.close()

bsize= float(sys.argv[2])
thebox = [-bsize,bsize,-bsize,bsize]

uselabels = len(sys.argv)>2
   
makepic(sys.argv[1],extend=15,box=thebox,labels=uselabels)
